language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql TESTSUITE=QueryEngineStandalone
      php: 5.3
    - env: DBTYPE=mysql TESTSUITE=QueryEngine
      php: 5.4
    - env: DBTYPE=sqlite TESTSUITE=QueryEngine
      php: 5.5
    - env: DBTYPE=postgres TESTSUITE=QueryEngine
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DBTYPE=postgres TESTSUITE=QueryEngine
    - php: 5.5

before_script:
  - bash .travis.sh $TESTSUITE

script:
  - cd ../phase3/extensions/WikibaseQueryEngine
  - phpunit --testsuite=$TESTSUITE

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always