language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - pwd
  - ls -lap
  - cd ..
  - pwd
  - ls -lap

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always