language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql TESTSUITE=Standalone
      php: 5.3
    - env: DBTYPE=mysql TESTSUITE=Integration
      php: 5.4
    - env: DBTYPE=sqlite TESTSUITE=Integration
      php: 5.5
    - env: DBTYPE=postgres TESTSUITE=Integration
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DBTYPE=postgres TESTSUITE=Integration

before_script: bash .travis.sh $TESTSUITE

script:
  - if [ "$TESTSUITE" == "Integration" ] ; then cd ../phase3/extensions/WikibaseQueryEngine ; fi
  - phpunit --testsuite=QueryEngine$TESTSUITE --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
