language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DBTYPE=mysql
  - DBTYPE=sqlite
  - DBTYPE=postgres
  - STANDALONE=yes
  - STANDALONE=no

matrix:
  allow_failures:
    - env: DBTYPE=postgres
  include:
    - env: DBTYPE=mysql
    - env: DBTYPE=sqlite
    - env: DBTYPE=postgres
    - env: STANDALONE=yes
    - env: STANDALONE=no

before_script:
  - bash .travis.sh
  - cd ../phase3/extensions/WikibaseQueryEngine

script:

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always