language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DB=mysql
      php: 5.3
    - env: DB=sqlite
      php: 5.4
    - env: DB=mysql
      php: 5.5
    - env: DB=sqlite
      php: 5.6
    - env: DB=mysqli
      php: 5.6
    - env: DB=sqlite
      php: hhvm
    - env: DB=pgsql POSTGRESQL_VERSION=9.1
      php: 5.3
    - env: DB=pgsql POSTGRESQL_VERSION=9.3
      php: 5.6
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - php: hhvm
    - env: DB=pgsql POSTGRESQL_VERSION=9.1
    - env: DB=pgsql POSTGRESQL_VERSION=9.3

before_script:
  - composer install --prefer-source
  - sh tests/travis/before_script.sh

script:
  - phpunit -c tests/travis/$DB.travis.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
