language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql
      php: 5.3
    - env: DBTYPE=mysql
      php: 5.4
    - env: DBTYPE=sqlite
      php: 5.5
    - env: DBTYPE=sqlite
      php: 5.6
    - env: DBTYPE=sqlite
      php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script:
  - composer install --prefer-source

script:
  - mysql --user root < tests/createTestDB.sql
  - phpunit

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
