language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DB=mysql
      php: 5.5
    - env: DB=sqlite
      php: 5.6
    - env: DB=mysqli
      php: 7
    - env: DB=sqlite
      php: hhvm
    - env: DB=pgsql POSTGRESQL_VERSION=9.1
      php: 5.5
    - env: DB=pgsql POSTGRESQL_VERSION=9.3
      php: 5.6
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DB=pgsql POSTGRESQL_VERSION=9.1
    - env: DB=pgsql POSTGRESQL_VERSION=9.3

install: travis_retry composer install

before_script: sh tests/travis/before_script.sh

script: phpunit -c tests/travis/$DB.travis.xml

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
