language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DBTYPE=mysql
  - DBTYPE=sqlite
  - DBTYPE=postgres

matrix:
  allow_failures:
    - env: DBTYPE=postgres

before_script:
  - bash .travis.sh

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always