language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cd ..
  - pwd
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/core.git phase3 --depth 1
  - cd phase3
  - php maintenance/install.php --dbtype sqlite --dbuser foo --dbpass bar --pass nyan --dbpath . TravisWiki admin
  - cd extensions
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Diff.git
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/DataValues.git
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Ask.git
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Wikibase.git
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/WikibaseQueryEngine.git
  - cd WikibaseQueryEngine

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always